include/materials/RedbackMechMaterialDP.h
src/materials/RedbackMechMaterial.C
src/materials/RedbackMechMaterialDP.C

#17 Cleanup damage mechanics and add tests and documentation further work on the expressions of mechanics

#17 Cleanup damage mechanics and add tests and documentation further work on mechanics

---

meshes/cylinder_Y.geo

#32 attempt 2

---

doc/installation/Leonardi/install.sh
doc/installation/Leonardi/test-stable-moose.pbs

#30 - merge new version of leonardi install scripts into devel branch.

30 leonardi

---

src/materials/RedbackMaterial.C

#43 restoring code again

---

meshes/cylinder_coarse.geo

#43 restoring code

---

src/timesteppers/ReturnMapIterDT.C

API update necessary to compile against the latest MOOSE.

Update due to MOOSE API change

---

src/materials/RedbackMaterial.C

Added gravity as a (vector) function

43 restoring code

---

src/auxkernels/RedbackPolarTensorMaterialAux.C

Last difference between manman's branch with master

#43 fixed error in polar auxkernel

---

scripts/raijin/.profile
scripts/raijin/install.pbs
scripts/raijin/readme.txt

Installation instructions for Raijin@NCI.
See https://github.com/pou036/redback/wiki/MOOSE%20on%20Raijin@NCI

#43 #107 Raijin installation scripts

---

include/materials/RedbackMechMaterial.h
src/materials/RedbackMechMaterial.C

preparation for incoming idaholab/moose#8719

switch declarePropertyOld to getMaterialPropertyOld

---

include/actions/RankTwoScalarAction.h
src/actions/RankTwoScalarAction.C
src/base/RedbackApp.C

Create postprocessors for calculating invariants of homogenized tensors

#43 new action to use the new postprocessor RankTwoScalarPostprocessor

---

include/materials/RedbackMechMaterialCCanisotropic.h
include/materials/RedbackMechMaterialDP.h
include/materials/RedbackMechMaterialElastic.h
include/materials/RedbackMechMaterialExpCC.h
include/materials/RedbackMechMaterialJ2.h
src/base/RedbackApp.C
src/materials/RedbackMechMaterial.C
src/materials/RedbackMechMaterialExpCC.C
src/materials/RedbackMechMaterialJ2.C

It will test the importance of one particular term in the flow law.
To be used for Tengatini fits.

#43 Implemented new material 

---

src/meshmodifiers/ElementFileSubdomain.C

Update for moose api changes

---

src/meshmodifiers/ElementFileSubdomain.C

please merge quickly if you can

Update to current libmesh apis

---

tests/image_meshing/image_reader.i

#195 updated image reader input test file

---

.gitignore
include/postprocessors/PointValueFileWriter.h
include/postprocessors/RankTwoScalarPostprocessor.h
src/postprocessors/PointValueFileWriter.C
src/postprocessors/RankTwoScalarPostprocessor.C

Needed for MOOSE maintenance: https://github.com/idaholab/moose/pull/25403

Used const getValue()

---

Makefile
unit/Makefile

Update to new MOOSE module name

---

Makefile
unit/Makefile

Revert "Update to new MOOSE module name"

---

Makefile
src/base/RedbackApp.C
unit/Makefile

refs idaholab/moose#25584
this is a follow up 
the previous PR did not do enough
the MOOSE PR is merged. this is safe to merge

Remove header that no longer exists

---

include/actions/RankTwoContractionAction.h
include/actions/RankTwoCstContractionAction.h
include/actions/RankTwoScalarVoidAction.h
include/auxkernels/RankTwoDoubleContraction.h
src/actions/RankTwoContractionAction.C
src/actions/RankTwoCstContractionAction.C
src/actions/RankTwoScalarVoidAction.C
src/actions/RedbackAction.C
src/auxkernels/RankTwoDoubleContraction.C

previous pull request failed Civet tests

#18 changed files to pass Civet tests
